export const BASE_SPEED = 12;
export const MIN_SPEED = 6;
export const MAX_SPEED = 22;
export const BOOST_MAX_SPEED = 44;
export const GLIDE_RATIO = 11;
export const BOOST_DRAIN = 24;
export const BOOST_MAX = 100;
export const SPEED_RING_MULT = 2;
export const SPEED_RING_TIME = 3;
export const THERMAL_LIFT = 4.4;
export const LANDING_AGL = 1.55;
export const FLARE_SINK = 1.5;
export const CRASH_SINK = 7.2;
export const MAX_COMBO = 5;
export const COMBO_WINDOW = 16;
export const MISS_TIME_PENALTY = 2;
export const NEAR_MISS_MIN = 1.6;
export const NEAR_MISS_MAX = 7.2;
export const WORLD_SIZE = 1600;
export const RING_SCORE = { green: 500, gold: 1500, boost: 1000 } as const;
export const LANDING_SCORE = { bullseye: 5000, mid: 2500, outer: 1000 } as const;
export const STORAGE_KEY = 'aero-glide-progress';

// Paraglider 3D Geometry Constants
export const SPAN = 9.23;
export const CHORD = 2.28;
export const CANOPY_Y = 3.65;
export const SEGS_X = 24;
export const SEGS_Z = 16;
