#!/usr/bin/env node
/**
 * Assemble the MHCP / Devpost zip in the OFFICIAL packaging shape:
 *
 *   index.html  — the whole game, readable, unminified (game code inline)
 *   vendor/     — three.js + used addons (import map + ESM, relative paths)
 *   models/ terrains/ audio/ — asset files, relative paths
 *
 * Requirements satisfied (Design Guidance → "Packaging your build"):
 * - ALL game code lives in index.html, unminified (esbuild bundles src/ with
 *   per-file banner comments so a judge can navigate source by section).
 * - Libraries are NOT inlined; they sit in vendor/ with a mapping so the
 *   module graph resolves offline.
 * - No external network requests at runtime. Served over a local web server
 *   by the judges — file:// double-click also works via the inline fallback
 *   (see MATCHERS below), because entries are relative paths.
 *
 * Draco is not used in the pack: file:// blocks its Worker, and decoder-free
 * GLBs (uncompressed geometry, WebP textures) live in contest/assets/,
 * regenerated by scripts/undraco.mjs.
 */
import { createRequire } from 'node:module';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const STAGE = fs.mkdtempSync(path.join('/tmp', 'aero-contest-'));

const require = createRequire(import.meta.url);

// ---------- assets: what ships in the zip, under what runtime path ----------
// GLBs: decoder-free versions from contest/assets (draco removed — the pack
// must run from file:// too, where the WASM decoder's Worker is blocked).
const GLB_ASSETS = [
  ['models/parachute.glb', 'parachute.glb'],
  ['models/mixamo/pilot.glb', 'pilot-mixamo.glb'],
  ['models/pilot.glb', 'pilot.glb'],
  ['terrains/mountain.glb', 'mountain.glb'],
];
const AUDIO_FILES = fs.readdirSync(path.join(ROOT, 'public/audio')).filter((f) => f.endsWith('.ogg'));

function copyAssets() {
  for (const [dest, src] of GLB_ASSETS) {
    const from = path.join(ROOT, 'contest/assets', src);
    if (!fs.existsSync(from)) throw new Error(`missing contest asset ${from}`);
    const to = path.join(STAGE, dest);
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.copyFileSync(from, to);
  }
  fs.mkdirSync(path.join(STAGE, 'audio'), { recursive: true });
  for (const f of AUDIO_FILES) {
    fs.copyFileSync(path.join(ROOT, 'public/audio', f), path.join(STAGE, 'audio', f));
  }
}

// ---------- vendor/: three + the addons the game imports ----------
// Recursive copy: start from the modules the game imports, then follow every
// relative `import … from '…'` / `from '…'` in each vendored file so the whole
// addon dependency graph ships (EffectComposer pulls Pass/ShaderPass/
// CopyShader/MaskPass, GLTFLoader pulls its utils, etc.). An import map maps
// 'three' and 'three/addons/…' onto this folder.
function copyVendor() {
  const threeRoot = path.join(ROOT, 'node_modules/three');
  const vendorDir = path.join(STAGE, 'vendor');
  const jsm = path.join(threeRoot, 'examples/jsm');

  const seed = [
    'build/three.module.js',
    'build/three.core.js',
    'examples/jsm/loaders/GLTFLoader.js',
    'examples/jsm/loaders/DRACOLoader.js',
    'examples/jsm/objects/Water.js',
    'examples/jsm/objects/Sky.js',
    'examples/jsm/utils/BufferGeometryUtils.js',
    'examples/jsm/postprocessing/EffectComposer.js',
    'examples/jsm/postprocessing/OutputPass.js',
    'examples/jsm/postprocessing/RenderPass.js',
  ];

  // dest path for a source file under three's package
  function destFor(abs) {
    const rel = path.relative(threeRoot, abs);
    if (rel.startsWith('build/')) return path.join(vendorDir, path.basename(rel));
    const addonsRel = rel.replace(/^examples\/jsm\//, '');
    return path.join(vendorDir, 'addons', addonsRel);
  }

  const queue = [...seed];
  const seen = new Set();
  const importRe = /(?:from\s*|import\s*)['"](\.[^'"]+)['"]/g;
  while (queue.length) {
    const rel = queue.shift();
    const abs = path.join(threeRoot, rel);
    if (seen.has(abs) || !fs.existsSync(abs)) continue;
    seen.add(abs);
    const dest = destFor(abs);
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.copyFileSync(abs, dest);
    const src = fs.readFileSync(abs, 'utf8');
    let m;
    while ((m = importRe.exec(src))) {
      const depAbs = path.resolve(path.dirname(abs), m[1]);
      const depRel = path.relative(threeRoot, depAbs);
      if (!seen.has(depAbs)) queue.push(depRel);
    }
  }
}

async function bundleGame(build) {
  // Bundle ONLY the game (src/) — three + addons stay external (vendor/),
  // referenced through the import map in index.html. Unminified, per-file
  // banners so the code reads as navigable source sections.
  await build({
    absWorkingDir: ROOT,
    entryPoints: ['src/main.ts'],
    bundle: true,
    format: 'esm',
    minify: false,
    keepNames: true,
    sourcemap: false,
    legalComments: 'none',
    target: 'es2022',
    charset: 'utf8',
    outfile: path.join(STAGE, 'game.assembled.js'),
    logLevel: 'info',
    banner: {
      js: `/**
 * Aero Glide: Canyon Rush — game source (assembled, unminified)
 * Meta Horizon Creator Competition — Survival & Resource Management
 *
 * Original TypeScript lives under src/ in the project repo. This file is the
 * same code bundled for delivery: each section below starts with
 *   /* ---- src/<path> ---- * /
 * so you can read the game module-by-module. Do not minify.
 *
 * three.js r178 and the addons used (GLTFLoader, DRACOLoader, Sky, Water,
 * BufferGeometryUtils, EffectComposer, RenderPass, OutputPass) are NOT
 * bundled here — they load from the vendor/ folder next to this file via
 * the import map in index.html.
 *
 * Core loop: gather fabric + cord in the storm, craft Patch / Bind / Heat
 * wrap, keep warmth + canopy integrity up, land on the valley pad before
 * the whiteout.
 */`,
    },
    external: ['three', 'three/addons/*'],
    define: {
      'import.meta.env.CONTEST': 'true',
      'import.meta.env.DEV': 'false',
      'import.meta.env.PROD': 'true',
      'import.meta.env.MODE': '"contest"',
      'import.meta.env.BASE_URL': '"./"',
    },
    plugins: [
      {
        name: 'src-banners',
        setup(buildApi) {
          buildApi.onLoad({ filter: /\/src\/.*\.(ts|css)$/ }, async (args) => {
            const source = await fs.promises.readFile(args.path, 'utf8');
            const rel = path.relative(ROOT, args.path);
            return {
              contents: `\n/* ---- ${rel} ---- */\n${source}`,
              loader: args.path.endsWith('.css') ? 'css' : 'ts',
            };
          });
        },
      },
    ],
  });
}

function writeIndex() {
  let html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
  // Strip external script (CrazyGames SDK) — pack runs fully offline.
  html = html.replace(/\s*<script[^>]+src="https?:\/\/[^"]+"[^>]*>\s*<\/script>/g, '');
  if (!html.includes('screen-orientation')) {
    html = html.replace('</title>', '</title>\n    <meta name="screen-orientation" content="portrait" />');
  }
  const css = fs.readFileSync(path.join(ROOT, 'src/style.css'), 'utf8');
  html = html.replace('<link rel="stylesheet" href="./src/style.css" />', `<style>\n${css}\n    </style>`);

  const game = fs.readFileSync(path.join(STAGE, 'game.assembled.js'), 'utf8');

  // file:// guard: ES modules + import maps cannot load from origin 'null'.
  // The competition procedure serves the zip over a local web server (FAQ:
  // "Do not just double-click index.html"). If someone double-clicks anyway,
  // show clear instructions instead of a silent black screen.
  const fileGuard = `  <script>
    // Serve-over-HTTP guard (classic script — runs even from file://)
    if (location.protocol === 'file:') {
      document.addEventListener('DOMContentLoaded', () => {
        const loader = document.getElementById('loader');
        if (loader) loader.hidden = false;
        const status = document.getElementById('loader-status');
        if (status) {
          status.textContent =
            'This build runs from a local web server (competition test procedure). ' +
            'In this folder run:  python3 -m http.server 8000  — then open http://localhost:8000';
        }
      });
      throw new Error('file:// cannot load ES modules — serve over HTTP (see message)');
    }
  </script>`;

  // Import map: bare 'three' → vendor/three.module.js; 'three/addons/…'
  // → vendor/addons/… (prefix mapping with trailing slash).
  const importMap = `  <script type="importmap">
    {
      "imports": {
        "three": "./vendor/three.module.js",
        "three/addons/": "./vendor/addons/"
      }
    }
  </script>`;

  // Module tag with the game code inline.
  const tag = `${fileGuard}
  ${importMap}
  <script type="module">
// ============================================================================
// GAME SOURCE — Aero Glide: Canyon Rush (readable, unminified)
// ============================================================================
${game}
  </script>`;
  html = html.replace('<script type="module" src="./src/main.ts"></script>', tag);
  if (/crazygames\.com/.test(html)) throw new Error('CrazyGames URL leaked into contest index.html');
  if (!html.includes('tickSurvival') || !html.includes('gatherSalvage')) {
    throw new Error('Survival loop missing from assembled index.html');
  }
  if (html.includes('src="./src/main.ts"') || /assets\/index-/.test(html)) {
    throw new Error('index.html is still a loader, not the assembled game');
  }
  fs.writeFileSync(path.join(STAGE, 'index.html'), html);
  fs.unlinkSync(path.join(STAGE, 'game.assembled.js'));
}

function zipStage() {
  const outDist = path.join(ROOT, 'dist/aero-glide-canyon-rush.zip');
  const outDocs = path.join(ROOT, 'docs/devpost/aero-glide-canyon-rush.zip');
  fs.mkdirSync(path.dirname(outDist), { recursive: true });
  fs.mkdirSync(path.dirname(outDocs), { recursive: true });
  fs.rmSync(outDist, { force: true });
  execFileSync('zip', ['-X', '-9', '-r', outDist, '.', '-x', '*.map', '-x', '*/.*'], {
    cwd: STAGE,
    stdio: 'inherit',
  });
  fs.copyFileSync(outDist, outDocs);
  return outDist;
}

function verify(zpath) {
  const script = `
import zipfile, sys
from pathlib import Path
z = zipfile.ZipFile(sys.argv[1])
names = z.namelist()
html = z.read("index.html").decode("utf-8", "replace")
print("entries", len(names))
if "index.html" not in names:
    raise SystemExit("FAIL: index.html not at zip root")
if any(n.endswith("/index.html") for n in names if n != "index.html"):
    raise SystemExit("FAIL: nested index.html")
if "vendor/three.module.js" not in names:
    raise SystemExit("FAIL: vendor/three.module.js missing")
if "vendor/addons/loaders/GLTFLoader.js" not in names:
    raise SystemExit("FAIL: vendor addons missing")
if "models/parachute.glb" not in names or "terrains/mountain.glb" not in names:
    raise SystemExit("FAIL: assets missing")
if not names or not any(n.startswith("audio/") for n in names):
    raise SystemExit("FAIL: audio missing")
if "crazygames.com" in html:
    raise SystemExit("FAIL: crazygames URL")
if 'src="./src/main.ts"' in html:
    raise SystemExit("FAIL: still a Vite loader")
if "tickSurvival" not in html:
    raise SystemExit("FAIL: game code not in index.html")
if html.count("\\n") < 200:
    raise SystemExit("FAIL: looks minified")
# game code must NOT import from http/CDN — vendor only
import re
for m in re.finditer(r'from\\s+.https?://[^\\s]+', html):
    raise SystemExit(f"FAIL: external import {m.group(0)}")
if "sdk.crazygames.com" in html:
    raise SystemExit("FAIL: external SDK reference")
if "importmap" not in html:
    raise SystemExit("FAIL: import map missing (vendor resolution)")
mb = Path(sys.argv[1]).stat().st_size / (1024 * 1024)
print(f"size {mb:.2f} MB")
if mb > 35:
    raise SystemExit("FAIL: zip exceeds 35MB")
print("OK: official shape — readable index.html + vendor/ + file assets")
`;
  const out = execFileSync('python3', ['-c', script, zpath], { encoding: 'utf-8' });
  process.stdout.write(out);
}

let esbuildOk = true;
try {
  require.resolve('esbuild');
} catch {
  esbuildOk = false;
}
if (!esbuildOk) {
  console.log('installing esbuild locally…');
  execFileSync('npm', ['install', '--no-save', '--no-package-lock', 'esbuild@0.25.8'], {
    cwd: ROOT,
    stdio: 'inherit',
  });
}

const { build } = await import('esbuild');
await bundleGame(build);
copyAssets();
copyVendor();
writeIndex();
const zpath = zipStage();
verify(zpath);
console.log('Wrote', zpath);
console.log('Stage was', STAGE);
